### ISSUE TITLE
system_requirements() fails on non-debian based distros

### ISSUE THREAD

**Issue by BenStraubinger** [dimi309/conan-glew#3]
A change was made to verify libGL / libGLU are installed before building GLEW, but this fails on non-debian based distros.

See issue: https://github.com/dimi309/conan-glew/issues/1

For reference, my Fedora 23 x64 uses the following package names:
```
mesa-libGL-devel
mesa-libGLU-devel
```

:Could you please update `export/conanfile.py` to check for both sets of package names? (or check based on distro)

If `rpm` is available, you can check with: 
`$ rpm -qa | grep "mesa-libGL-devel\|mesa-libGLU-devel"`

Let me know if you need any help. I'll keep an eye out for a fix and confirm once verified.

**Comment by dimi309** [comment]
Sorry about that... Indeed I had only prepared the package for Debian-based distros and was wondering when this day would come :grin: I'll have it modified in a few hours and let you know.

**Comment by dimi309** [comment]
Ok! All packages have compiled without problems. There's just one remaining that is a bit slow. Of course, I don't have an rpm-based setup on Travis so you will have to force-build locally, but normally it should work now. Let me know if there are any more problems, and thanks again for the contribution!
