### ISSUE TITLE
MinGW build fail

### ISSUE THREAD

**Issue by adamros** [dimi309/conan-glew#6]
When you try to build GLEW from sources on MinGW, it will fail, because of "hack" for Windows:
```
glew/2.0.0@coding3d/stable:` ERROR: Package '720e37aee97783e0915ba39fb0d188977e0cc8d6' build failed
glew/2.0.0@coding3d/stable: WARN: Build folder D:\Users\adamros\.conan\data\glew\2.0.0\coding3d\stable\build\720e37aee97783e0915ba39fb0d188977e0cc8d6
ERROR: glew: invalid literal for int() with base 10: '5.1'
```
`

**Comment by dimi309** [comment]
I have not adapted the package to MinGW but, if someone makes the necessary changes, I'll be happy to accept a pull request.

**Comment by dimi309** [comment]
It's been a long time but the glew package can now be built on mingw 😄 
Note that it is now grouped in the same repository as my other conan packages, for which I am working on adding mingw support.
