### ISSUE TITLE
'devenv' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by phobos2077** [dimi309/conan-glew#7]
The script assumes "devenv" command being available in path, which is not by default. That's very strange assumption to make.

**Comment by dimi309** [comment]
Thanks for the feedback. "devenv" is available in the path on appveyor, which I am using for automated builds and it is also available in the command prompt provided by the installation of visual studio e.g. VS2015 x64 Native Tools Command prompt as far as I know. At least that is that case on my machine. But please do let me know if you think I'm missing something or if you can propose a better solution.

**Comment by phobos2077** [comment]
I am using Windows 7 x64. I have Visual Studio 2010, 2015 and 2017 all installed by ordinary means.

**Comment by dimi309** [comment]
Devenv should be available in the command prompt that appears in the start menu within the Visual Studio group. The link is named "VS2015 x64 Native Tools Command prompt" or something similar. The standard windows command prompt on the other hand does indeed not recognise the devenv command from what I have seen.

**Comment by dimi309** [comment]
It seems you were right and I was wrong (sorry ☹️). I just never ran conan from a plain command prompt and I thought it wasn't possible until I learned a couple of new things. I've fixed this now. (Note that the glew package is now grouped with my other conan contributions in the same repository).
